/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface AccountActivityLog {
  account_id: number | null;
  activity_type: string | null;
  city: string | null;
  country: string | null;
  created_at: Generated<string>;
  id: Generated<number | null>;
  ip_address: string | null;
  is_non_routable_ip: number | null;
  metadata: string | null;
  occurred_at: string | null;
  person_id: number;
  product: string | null;
  proxied_ip_address: string | null;
  region: string | null;
  service: string | null;
  source: string | null;
  sub_product: string | null;
  user_agent: string | null;
}

export interface AccountAliases {
  account_id: string | null;
  alias: string | null;
  canonical_name: string | null;
  confidence_score: string | null;
  created_at: string | null;
  id: string | null;
  last_seen_at: string | null;
  validation_count: string | null;
}

export interface AccountNameMap {
  canonical: string;
  institution: string | null;
  variant: string | null;
}

export interface Accounts {
  created_at: string | null;
  created_at_timestamp: Generated<string | null>;
  email: string | null;
  id: Generated<number>;
  metadata: string | null;
  person_id: number;
  service: string;
  username: string | null;
}

export interface Activities {
  date: string | null;
  details: string | null;
  id: string | null;
  location: string | null;
  name: string | null;
  notes: string | null;
  trip_id: string | null;
  type: string | null;
}

export interface ActivityEventMap {
  activity_id: Generated<number | null>;
  calendar_event_id: number;
  created_at: Generated<string>;
  match_method: string;
}

export interface ActivityLog {
  action: string | null;
  created_at: string | null;
  description: string | null;
  domain: string | null;
  entity_id: string | null;
  id: string | null;
  metadata: string | null;
}

export interface ActivityPeople {
  activity_id: string | null;
  person_id: string | null;
  role: string | null;
}

export interface ActivityTypes {
  category: string | null;
  created_at: string | null;
  description: string | null;
  id: string | null;
  name: string | null;
}

export interface AmazonOrders {
  carrier_name_and_tracking_number: string | null;
  created_at: Generated<string>;
  currency: string | null;
  gift_message: string | null;
  gift_sender_name: string | null;
  id: Generated<number | null>;
  order_date: string | null;
  order_id: string;
  order_status: string | null;
  payment_instrument_type: string | null;
  purchase_channel: Generated<string | null>;
  purchase_order_number: string | null;
  shipment_date: string | null;
  shipping_address_city: string | null;
  shipping_address_name: string | null;
  shipping_address_state: string | null;
  shipping_address_street_1: string | null;
  shipping_address_street_2: string | null;
  shipping_address_zip: string | null;
  shipping_option: string | null;
  source: Generated<string | null>;
}

export interface AmazonPurchases {
  amazon_orders_id: number | null;
  asin_isbn: string | null;
  carrier_name_and_tracking_number: string | null;
  category: string | null;
  currency: string | null;
  gift_message: string | null;
  gift_sender_name: string | null;
  id: string | null;
  item_serial_number: string | null;
  item_subtotal: string | null;
  item_subtotal_tax: string | null;
  item_total: string | null;
  order_date: string | null;
  order_id: string | null;
  order_status: string | null;
  payment_instrument_type: string | null;
  product_condition: string | null;
  purchase_channel: Generated<string | null>;
  purchase_order_number: string | null;
  purchase_price_per_unit: string | null;
  quantity: string | null;
  shipment_date: string | null;
  shipment_status: string | null;
  shipping_address_city: string | null;
  shipping_address_name: string | null;
  shipping_address_state: string | null;
  shipping_address_street_1: string | null;
  shipping_address_street_2: string | null;
  shipping_address_zip: string | null;
  shipping_option: string | null;
  title: string | null;
  transaction_place: string | null;
}

export interface AmazonReturns {
  amazon_orders_id: number | null;
  carrier_package_id: string | null;
  created_at: Generated<string>;
  currency: string | null;
  id: Generated<number | null>;
  order_id: string;
  resolution: string | null;
  return_amount: number | null;
  return_date: string | null;
  return_reason: string | null;
  return_ship_option: string | null;
  rma_id: string | null;
  tracking_id: string | null;
}

export interface Art {
  artist_id: number | null;
  collection: string | null;
  created_at: Generated<string>;
  date: string | null;
  dimensions: string | null;
  id: Generated<number | null>;
  is_favorite: Generated<number | null>;
  medium: string | null;
  movement: string | null;
  notes: string | null;
  period: string | null;
  title: string;
}

export interface ArtistProfiles {
  active_from: number | null;
  active_to: number | null;
  birth_place: string | null;
  created_at: Generated<string>;
  discipline: string | null;
  id: Generated<number | null>;
  movement: string | null;
  nationality: string | null;
  notes: string | null;
  person_id: number;
}

export interface Artworks {
  artist: string | null;
  artist_id: string | null;
  created_at: Generated<string>;
  date_acquired: string | null;
  dimensions: string | null;
  edition: string | null;
  format: string | null;
  frame_color: string | null;
  framed: Generated<number | null>;
  id: Generated<number | null>;
  image_path: string | null;
  is_favorite: Generated<number | null>;
  location: string | null;
  medium: string | null;
  notes: string | null;
  price: number | null;
  series: string | null;
  tags: string | null;
  title: string;
  updated_at: Generated<string>;
  year: number | null;
}

export interface BookHighlights {
  book_id: number | null;
  book_title: string | null;
  created_at: string | null;
  created_at_ts: Generated<string>;
  device_family: string | null;
  highlight_color: string | null;
  highlight_type: Generated<string | null>;
  id: Generated<number | null>;
  is_starred: Generated<number | null>;
  location: string | null;
  note: string | null;
  selected_text: string | null;
  source: Generated<string | null>;
  updated_at: string | null;
  word_count: number | null;
}

export interface Bookmarks {
  id: Generated<number | null>;
}

export interface Books {
  asin: string | null;
  author: string | null;
  category_path: string | null;
  cover_image_url: string | null;
  created_at: Generated<string>;
  description: string | null;
  enriched_at: string | null;
  id: Generated<number | null>;
  isbn_10: string | null;
  isbn_13: string | null;
  print_length: number | null;
  publication_date: string | null;
  publisher: string | null;
  rating: string | null;
  source: Generated<string | null>;
  title: string;
}

export interface BookShelves {
  book_id: number | null;
  book_title: string | null;
  created_at: Generated<string>;
  id: Generated<number | null>;
  is_current: Generated<number | null>;
  reading_progress_pct: number | null;
  shelf_name: string;
  source: Generated<string | null>;
}

export interface BusinessPlanningInputs {
  Metric: string | null;
  Values: string | null;
}

export interface BusinessPlanningRevenue {
  "Annual Subscription (ARR)": string | null;
  "Annual Subscription (MRR)": string | null;
  "Monthly Subscription (ARR)": string | null;
  "Monthly Subscription (MRR)": string | null;
}

export interface CalendarEventCategories {
  color_code: string | null;
  created_at: string | null;
  description: string | null;
  display_order: string | null;
  emoji: string | null;
  icon_name: string | null;
  id: string | null;
  name: string | null;
}

export interface CalendarEventDetails {
  attendees: string | null;
  calendar_name: string | null;
  confidence_score: string | null;
  created: string | null;
  description: string | null;
  dtstamp: string | null;
  end: string | null;
  extracted_detail: string | null;
  extracted_person: string | null;
  format_class: string | null;
  id: string | null;
  is_all_day: number | null;
  last_modified: string | null;
  location: string | null;
  metadata: string | null;
  organizer: string | null;
  parent_tag_id: string | null;
  parent_tag_name: string | null;
  parent_tag_path: string | null;
  recurrence_rule: string | null;
  source: string | null;
  source_row_id: number | null;
  start: string | null;
  status: string | null;
  summary: string | null;
  tag_id: string | null;
  tag_name: string | null;
  tag_path: string | null;
  trip_id: number | null;
  uid: string | null;
}

export interface CalendarEventOccurrences {
  description: string | null;
  expanded_at: Generated<string>;
  expansion_version: string;
  expansion_window_end: string | null;
  expansion_window_start: string | null;
  id: Generated<number | null>;
  is_all_day: Generated<number>;
  is_cancelled: Generated<number>;
  is_excluded: Generated<number>;
  is_generated: Generated<number>;
  is_override: Generated<number>;
  location: string | null;
  occurrence_date: string | null;
  occurrence_end_utc: string | null;
  occurrence_key: string;
  occurrence_start_utc: string;
  raw_event_id: number;
  recurrence_id_utc: string | null;
  status: string | null;
  summary: string | null;
  uid: string;
}

export interface CalendarEventPeople {
  created_at: Generated<string>;
  event_id: number;
  person_id: number;
  role: Generated<string | null>;
  source: string | null;
}

export interface CalendarEventPlaceDetails {
  calendar_name: string | null;
  city: string | null;
  country: string | null;
  country_code: string | null;
  description: string | null;
  end: string | null;
  event_metadata: string | null;
  formatted_address: string | null;
  geocoded_at: string | null;
  id: string | null;
  is_all_day: number | null;
  latitude: number | null;
  location: string | null;
  longitude: number | null;
  place_id: number | null;
  place_metadata: string | null;
  place_name: string | null;
  place_type: string | null;
  place_url: string | null;
  postal_code: string | null;
  source: string | null;
  source_row_id: number | null;
  start: string | null;
  state: string | null;
  status: string | null;
  summary: string | null;
  tag_id: string | null;
  trip_id: number | null;
  uid: string | null;
}

export interface CalendarEvents {
  activity_type: string | null;
  attendees: string | null;
  calendar_name: string | null;
  category_id: string | null;
  confidence_score: string | null;
  created_at: string | null;
  description: string | null;
  dtstamp: string | null;
  end_time: string | null;
  event_type_id: string | null;
  extracted_detail: string | null;
  extracted_person: string | null;
  format_class: string | null;
  id: string | null;
  is_all_day: Generated<number | null>;
  last_modified: string | null;
  location: string | null;
  metadata: string | null;
  organizer: string | null;
  place_id: number | null;
  recurrence_rule: string | null;
  source: string | null;
  source_row_id: number | null;
  start_time: string | null;
  status: string | null;
  summary: string | null;
  trip_id: number | null;
  uid: string | null;
  updated_at: string | null;
}

export interface CalendarEventsRaw {
  all_day: Generated<number>;
  attendees_json: string | null;
  calendar_name: string | null;
  categories_json: string | null;
  classification: string | null;
  created_utc: string | null;
  description: string | null;
  dtend_kind: Generated<string>;
  dtend_raw: string | null;
  dtend_tzid: string | null;
  dtend_utc: string | null;
  dtstamp_utc: string | null;
  dtstart_kind: Generated<string>;
  dtstart_raw: string | null;
  dtstart_tzid: string | null;
  dtstart_utc: string | null;
  duration_raw: string | null;
  event_type: string | null;
  exdate_raw: string | null;
  exrule_raw: string | null;
  id: Generated<number | null>;
  import_batch_id: string;
  ingested_at: Generated<string>;
  last_modified_utc: string | null;
  location: string | null;
  method: string | null;
  organizer: string | null;
  parse_error: string | null;
  parse_warnings_json: string | null;
  prodid: string | null;
  raw: string;
  rdate_raw: string | null;
  recurrence_id_raw: string | null;
  recurrence_id_utc: string | null;
  rrule_raw: string | null;
  sequence: number | null;
  source_file: string;
  source_hash: string | null;
  source_path: string | null;
  source_system: string | null;
  status: string | null;
  summary: string | null;
  transp: string | null;
  tzid: string | null;
  uid: string;
  url: string | null;
}

export interface CalendarEventTypeMappings {
  category_id: string | null;
  confidence_score: string | null;
  created_at: string | null;
  event_type_id: string | null;
  extracted_detail: string | null;
  extracted_person: string | null;
  format_class: string | null;
  id: string | null;
  notes: string | null;
  raw_summary: string | null;
}

export interface CalendarEventTypes {
  category_id: string | null;
  created_at: string | null;
  description: string | null;
  emoji: string | null;
  format_class: string | null;
  frequency_score: string | null;
  id: string | null;
  is_active: string | null;
  name: string | null;
  parsing_rule: string | null;
}

export interface CalendarSummaryMap {
  event_id: string | null;
  id: string | null;
  migration_timestamp: string | null;
  new_summary: string | null;
  original_summary: string | null;
  people_extracted: string | null;
  type_detected: string | null;
  yaml_valid: string | null;
}

export interface CalendarTags {
  created_at: Generated<string>;
  depth: Generated<number>;
  description: string | null;
  full_path: string;
  id: Generated<number | null>;
  name: string;
  parent_id: number | null;
  slug: string;
}

export interface CalImportBatches {
  error_count: Generated<number>;
  event_count: Generated<number>;
  file_count: Generated<number>;
  id: string | null;
  imported_at: string;
  source_paths_json: string | null;
  warning_count: Generated<number>;
}

export interface CareerApplications {
  applied_at: string | null;
  company: string;
  cover_letter_url: string | null;
  created_at: Generated<string>;
  current_stage: string | null;
  id: Generated<number | null>;
  job_posting_url: string | null;
  legacy_id: string | null;
  location: string | null;
  notes: string | null;
  referred_by: string | null;
  resume_url: string | null;
  salary_expectation: string | null;
  source: string | null;
  status: string | null;
  title: string;
  updated_at: Generated<string>;
}

export interface CareerApplicationStages {
  application_id: number;
  created_at: Generated<string>;
  entered_at: string | null;
  exited_at: string | null;
  id: Generated<number | null>;
  notes: string | null;
  stage: string;
}

export interface CareerCompanyVelocity {
  applications: string | null;
  avg_days_to_outcome: string | null;
  company: string | null;
  status: string | null;
}

export interface CareerEducation {
  activities: string | null;
  created_at: Generated<string>;
  degree: string | null;
  end_date: string | null;
  field_of_study: string | null;
  id: Generated<number | null>;
  notes: string | null;
  school: string;
  start_date: string | null;
}

export interface CareerInterviews {
  company: string | null;
  date_applied: string | null;
  id: Generated<number>;
  location: string | null;
  phone_screen: string | null;
  status: string | null;
}

export interface CareerOffers {
  application_id: number | null;
  base_salary: number | null;
  bonus: number | null;
  created_at: Generated<string>;
  currency: Generated<string | null>;
  decision: string | null;
  decision_at: string | null;
  equity: string | null;
  id: Generated<number | null>;
  notes: string | null;
  signing_bonus: number | null;
  total_comp: number | null;
}

export interface CareerPipeline {
  applied_at: string | null;
  company: string | null;
  current_stage: string | null;
  days_in_stage: string | null;
  days_since_applied: string | null;
  id: number | null;
  job_posting_url: string | null;
  location: string | null;
  referred_by: string | null;
  salary_expectation: string | null;
  source: string | null;
  stage_notes: string | null;
  title: string | null;
}

export interface CareerPositions {
  address: string | null;
  company: string;
  contact_name: string | null;
  contact_phone: string | null;
  created_at: Generated<string>;
  currency: string | null;
  description: string | null;
  end_date: string | null;
  id: Generated<number | null>;
  is_current: Generated<number | null>;
  is_target: Generated<number | null>;
  location: string | null;
  project_status: string | null;
  record_type: Generated<string>;
  salary_high: number | null;
  salary_low: number | null;
  source: Generated<string | null>;
  start_date: string | null;
  title: string;
  url: string | null;
}

export interface CareerProfile {
  birth_date: string | null;
  created_at: Generated<string>;
  email: string | null;
  first_name: string | null;
  headline: string | null;
  id: Generated<number | null>;
  industry: string | null;
  last_name: string | null;
  linkedin_url: string | null;
  location: string | null;
  phone: string | null;
  registered_at: string | null;
  summary: string | null;
  twitter_handles: string | null;
  websites: string | null;
}

export interface CareerSourceSummary {
  active: string | null;
  applications: string | null;
  progressed: string | null;
  rejected: string | null;
  source: string | null;
}

export interface CareerStageTimeline {
  application_id: number | null;
  company: string | null;
  days_in_stage: string | null;
  entered_at: string | null;
  exited_at: string | null;
  stage: string | null;
  stage_notes: string | null;
  stage_number: string | null;
  status: string | null;
  title: string | null;
}

export interface CareerStageVelocity {
  avg_days: string | null;
  count: string | null;
  max_days: string | null;
  min_days: string | null;
  stage: string | null;
}

export interface CareerWeeklyApplications {
  active: string | null;
  applications: string | null;
  rejected: string | null;
  week: string | null;
  withdrew: string | null;
}

export interface Concerts {
  artist: string | null;
  city: string | null;
  date: string | null;
  id: Generated<number>;
  state: string | null;
  type: string | null;
  venue: string | null;
}

export interface Dining {
  city: string | null;
  date: string | null;
  id: Generated<number | null>;
  meal: string | null;
  name: string;
  notes: string | null;
  trip_id: number | null;
}

export interface Domains {
  id: string | null;
  purchased: string | null;
  registrar: string | null;
  site: string | null;
}

export interface Entities {
  created_at: Generated<string | null>;
  domain: string;
  entity_subtype: string | null;
  entity_type: string;
  id: string | null;
  metadata: string | null;
  status: Generated<string | null>;
  title: string;
  updated_at: Generated<string | null>;
}

export interface EventPeople {
  event_id: number;
  person_id: number;
  role: string | null;
}

export interface EventPlaces {
  event_id: number | null;
  id: Generated<number | null>;
  place_id: number | null;
}

export interface Events {
  body: string | null;
  category: string;
  created_at: Generated<string>;
  date: string;
  date_end: string | null;
  date_precision: string;
  id: Generated<number | null>;
  sentiment: string | null;
  source: string | null;
  title: string;
  updated_at: Generated<string>;
}

export interface EventsFts {
  body: string | null;
  title: string | null;
}

export interface EventsFtsConfig {
  k: string;
  v: string | null;
}

export interface EventsFtsData {
  block: Buffer | null;
  id: Generated<number | null>;
}

export interface EventsFtsDocsize {
  id: Generated<number | null>;
  sz: Buffer | null;
}

export interface EventsFtsIdx {
  pgno: string | null;
  segid: string;
  term: string;
}

export interface EventTags {
  event_id: number;
  tag: string;
}

export interface Favorites {
  category: string | null;
  Comment: string | null;
  Note: string | null;
  Title: string | null;
  URL: string | null;
}

export interface FinanceAccountLabels {
  account_id: number;
  confidence: Generated<number>;
  created_at: Generated<string>;
  effective_from: string | null;
  effective_to: string | null;
  id: Generated<number | null>;
  institution: string | null;
  is_generic: Generated<number>;
  label: string;
  label_kind: string;
  note: string | null;
  resolves_to_account: Generated<number>;
  source: Generated<string>;
}

export interface FinanceAccountLedgerEntries {
  account_id: number;
  account_mask: string | null;
  balance_delta_cents: number;
  created_at: string | null;
  currency_code: Generated<string>;
  description: string;
  id: Generated<number | null>;
  ledger_entry_kind: Generated<string>;
  note: string | null;
  posted_on: string;
  posting_status: Generated<string>;
  source_fingerprint: string;
  updated_at: string | null;
}

export interface FinanceAccounts {
  account_type: Generated<string>;
  closed_on: string | null;
  currency_code: Generated<string>;
  id: Generated<number | null>;
  include_in_net_worth: Generated<number>;
  institution: string | null;
  lifecycle_status: Generated<string>;
  name: string;
  opened_on: string | null;
}

export interface FinanceAccountStatementPeriods {
  account_id: number;
  certification_status: Generated<string>;
  closing_balance_cents: Generated<number>;
  created_at: Generated<string>;
  currency_code: Generated<string>;
  evidence_path: string | null;
  id: Generated<number | null>;
  note: string | null;
  opening_balance_cents: Generated<number>;
  period_end_on: string;
  period_start_on: string;
  source: Generated<string>;
}

export interface FinanceCategories {
  id: Generated<number | null>;
  name: string;
  parent_id: number | null;
}

export interface FinanceCreditScores {
  bureau: string | null;
  date: string | null;
  id: Generated<number | null>;
  score: number | null;
  source: string | null;
}

export interface FinanceExpenses {
  billing_period: string | null;
  category: string | null;
  cost: number | null;
  end_date: string | null;
  id: Generated<number>;
  payee: string | null;
  situation: string | null;
  start_date: string | null;
  type: string | null;
}

export interface FinanceIncomes {
  gross_amount: number | null;
  id: Generated<number | null>;
  location: string | null;
  net_amount: number | null;
  source: string | null;
  tax_details: string | null;
  type: string | null;
  year: number | null;
}

export interface FinanceLedgerEntryAnnotations {
  category_assignment_source: Generated<string>;
  category_id: number | null;
  created_at: Generated<string>;
  excluded: Generated<number>;
  ledger_entry_id: Generated<number | null>;
  recurring: Generated<number>;
  updated_at: string | null;
}

export interface GoogleActivities {
  "Activity City": string | null;
  "Activity Country": string | null;
  "Activity Region": string | null;
  "Activity Timestamp": string | null;
  "Activity Type": string | null;
  "Gaia ID": string | null;
  "Gmail Access Channel": string | null;
  "IP Address": string | null;
  "Is Non-routable IP Address": string | null;
  "Product Name": string | null;
  "Proxiedhost IP Address": string | null;
  "Sub-Product Name": string | null;
  "User Agent String": string | null;
}

export interface GoogleDeviceRegistry {
  brand: string | null;
  created_at: Generated<string>;
  device_type: string | null;
  gaia_id: string | null;
  id: Generated<number | null>;
  last_location: string | null;
  marketing_name: string | null;
  model: string | null;
  os: string | null;
  os_version: string | null;
  user_name: string | null;
}

export interface GoogleDevices {
  "Brand Name": string | null;
  "Device Last Location": string | null;
  "Device Model": string | null;
  "Device Type": string | null;
  "Gaia ID": string | null;
  "Marketing Name": string | null;
  OS: string | null;
  "OS Version": string | null;
  "User Given Name": string | null;
}

export interface GooglePlayPurchases {
  created_at: Generated<string>;
  currency: Generated<string | null>;
  document_type: string | null;
  id: Generated<number | null>;
  price: number | null;
  purchased_at: string;
  source_file: string | null;
  title: string;
}

export interface GoogleSaved {
  created_at: Generated<string>;
  id: Generated<number | null>;
  note: string | null;
  saved_at: string | null;
  source: string;
  title: string | null;
  url: string | null;
}

export interface GooseDbVersion {
  id: Generated<number | null>;
  is_applied: number;
  tstamp: Generated<string | null>;
  version_id: number;
}

export interface HealthActivities {
  activity_type: string | null;
  calories: number | null;
  created_at: Generated<string>;
  distance_m: number | null;
  duration_s: number | null;
  ended_at: string | null;
  gps_path: string | null;
  id: Generated<number | null>;
  intensity: number | null;
  metadata: string | null;
  source: Generated<string | null>;
  started_at: string;
}

export interface HealthBloodPressure {
  comments: string | null;
  created_at: Generated<string>;
  diastolic: number | null;
  heart_rate_bpm: number | null;
  id: Generated<number | null>;
  measured_at: string;
  source: Generated<string>;
  systolic: number | null;
}

export interface HealthBodyComposition {
  bone_pct: number | null;
  created_at: Generated<string>;
  date: string;
  fat_free_mass_kg: number | null;
  fat_pct: number | null;
  id: Generated<number | null>;
  muscle_pct: number | null;
  pulse_wave_velocity: number | null;
  source: Generated<string | null>;
  vascular_age: number | null;
  vo2_max: number | null;
  water_pct: number | null;
}

export interface HealthDaily {
  calories_active: number | null;
  calories_passive: number | null;
  created_at: Generated<string>;
  date: string;
  distance_m: number | null;
  elevation_m: number | null;
  id: Generated<number | null>;
  source: Generated<string | null>;
  steps: number | null;
}

export interface HealthHeartRate {
  bpm: string | null;
  created_at: Generated<string>;
  duration_s: string | null;
  id: Generated<number | null>;
  level: string | null;
  skin_temp: string | null;
  source: Generated<string | null>;
  spo2_quality: string | null;
  started_at: string;
  state: string | null;
}

export interface HealthHeightMeasurements {
  comments: string | null;
  created_at: Generated<string>;
  height_in: number | null;
  id: Generated<number | null>;
  measured_at: string;
  source: Generated<string>;
}

export interface HealthLocations {
  accuracy: number | null;
  altitude: number | null;
  created_at: Generated<string>;
  duration_s: string | null;
  id: Generated<number | null>;
  latitude: number | null;
  longitude: number | null;
  source: Generated<string | null>;
  speed: number | null;
  started_at: string;
}

export interface HealthLog {
  id: string | null;
  metric_type: string | null;
  platform: string | null;
  source_file: string | null;
  timestamp: string | null;
  unit: string | null;
  value: string | null;
}

export interface HealthRecords {
  id: Generated<number | null>;
}

export interface HealthSleep {
  avg_heart_rate: string | null;
  awake_seconds: string | null;
  deep_sleep_seconds: string | null;
  duration_to_sleep_seconds: string | null;
  duration_to_wake_seconds: string | null;
  end_time: string | null;
  id: string | null;
  light_sleep_seconds: string | null;
  max_heart_rate: string | null;
  min_heart_rate: string | null;
  rem_sleep_seconds: string | null;
  snoring_episodes: string | null;
  snoring_seconds: string | null;
  source: string | null;
  start_time: string | null;
  wake_up_count: string | null;
}

export interface HealthSupplements {
  category: string | null;
  details_dose: string | null;
  id: Generated<number | null>;
  notes: string | null;
}

export interface HealthTracker {
  calories: number | null;
  created_at: Generated<string>;
  distance_m: number | null;
  duration_s: string | null;
  id: Generated<number | null>;
  intensity: number | null;
  source: Generated<string | null>;
  started_at: string;
  steps: number | null;
}

export interface HealthVitamins {
  Category: string | null;
  "Details / Dose": string | null;
  Notes: string | null;
}

export interface HealthWeightMeasurements {
  bone_mass_kg: number | null;
  comments: string | null;
  created_at: Generated<string>;
  fat_mass_kg: number | null;
  hydration_kg: number | null;
  id: Generated<number | null>;
  measured_at: string;
  muscle_mass_kg: number | null;
  source: string;
  weight_kg: number | null;
}

export interface HingeMedia {
  from_social_media: string | null;
  type: string | null;
  url: string | null;
}

export interface HingePrompts {
  created: string | null;
  id: string | null;
  prompt: string | null;
  text: string | null;
  type: string | null;
  user_updated: string | null;
}

export interface HingeUser {
  account: string | null;
  devices: string | null;
  identity: string | null;
  location: string | null;
  preferences: string | null;
  profile: string | null;
}

export interface IncomeLog {
  currency: Generated<string>;
  gross_cents: number | null;
  id: Generated<number | null>;
  location: string | null;
  net_cents: number | null;
  notes: string | null;
  source: string;
  year: number;
}

export interface Item {
  createdAt: string | null;
  id: string | null;
  itemId: string | null;
  itemType: string | null;
  listId: string | null;
  type: string | null;
  updatedAt: string | null;
  userId: string | null;
}

export interface LifeEvents {
  category: string | null;
  city: string | null;
  country: string | null;
  date_end: string | null;
  date_precision: string | null;
  description: string | null;
  id: string | null;
  location: string | null;
  people: string | null;
  sentiment: string | null;
  start: string | null;
  state: string | null;
  summary: string | null;
  tags: string | null;
}

export interface List {
  createdAt: string | null;
  description: string | null;
  id: string | null;
  isPublic: string | null;
  name: string | null;
  ownerId: string | null;
  updatedAt: string | null;
}

export interface ListInvite {
  accepted: string | null;
  acceptedAt: string | null;
  createdAt: string | null;
  invitedUserEmail: string | null;
  invitedUserId: string | null;
  listId: string | null;
  token: string | null;
  updatedAt: string | null;
  userId: string | null;
}

export interface LlmConversations {
  cost: number | null;
  created_at: string | null;
  id: string | null;
  message_count: number | null;
  model: string | null;
  provider: string | null;
  source: Generated<string>;
  system_text: string | null;
  temperature: number | null;
  title: string | null;
  updated_at: string | null;
}

export interface LlmMessages {
  content: string | null;
  conversation_id: string | null;
  cost: number | null;
  created_at: string | null;
  id: string | null;
  input_tokens: number | null;
  model: string | null;
  output_tokens: number | null;
  provider: string | null;
  role: string;
  source: Generated<string>;
}

export interface LocationsCities {
  Continent: string | null;
  Country: string | null;
  "﻿Name": string | null;
  Status: string | null;
}

export interface MediaActivityLog {
  account_id: number | null;
  activity_type: string | null;
  collection_name: string | null;
  content_id: string | null;
  created_at: Generated<string>;
  id: Generated<number | null>;
  media_type: string | null;
  metadata: string | null;
  occurred_at: string | null;
  person_id: number;
  platform: string | null;
  source: string | null;
  title: string | null;
}

export interface MediaBacklog {
  added_date: string | null;
  content_type: string | null;
  device: string | null;
  episode: number | null;
  first_watched: string | null;
  id: Generated<number | null>;
  last_watched: string | null;
  letterboxd_id: string | null;
  notes: string | null;
  quality: string | null;
  rating: number | null;
  season: number | null;
  seconds_watched: number | null;
  series_name: string | null;
  sources: string | null;
  status: Generated<string | null>;
  title: string;
  watch_count: Generated<number | null>;
}

export interface MediaCollectionItems {
  added_at: string | null;
  collection_id: number;
  created_at: Generated<string>;
  id: Generated<number | null>;
  item_id: number;
  metadata: string | null;
  position: number | null;
  raw_group_name: string | null;
  raw_recorded_at: string | null;
  raw_title: string | null;
  raw_type: string | null;
  removed_at: string | null;
  source_row_id: number | null;
  source_table: string | null;
  status: Generated<string>;
  updated_at: Generated<string>;
}

export interface MediaCollections {
  account_id: number | null;
  collection_type: string | null;
  created_at: string | null;
  description: string | null;
  external_id: string | null;
  id: Generated<number | null>;
  metadata: string | null;
  name: string | null;
  person_id: number;
  platform: string | null;
  sort_order: string | null;
  source: string | null;
  updated_at: string | null;
  visibility: string | null;
}

export interface MediaGames {
  game_title: string | null;
  id: string | null;
  platform: string | null;
  release_year: string | null;
}

export interface MediaItemActivities {
  account_id: number | null;
  activity_type: string;
  confidence: Generated<number>;
  created_at: Generated<string>;
  id: Generated<number | null>;
  item_id: number;
  metadata: string | null;
  occurred_at: string;
  person_id: number;
  provider: string | null;
  source_event_key: string;
  source_row_id: number;
  source_table: string;
}

export interface MediaItemActivityDetails {
  activity_type: string | null;
  canonical_title: string | null;
  confidence: number | null;
  created_at: string | null;
  id: number | null;
  item_id: number | null;
  media_kind: string | null;
  metadata: string | null;
  occurred_at: string | null;
  person_id: number | null;
  person_name: string | null;
  provider: string | null;
  source_event_key: string | null;
  source_row_id: number | null;
  source_table: string | null;
}

export interface MediaItemDetails {
  activity_count: string | null;
  canonical_title: string | null;
  collection_count: string | null;
  collection_entry_count: string | null;
  collection_platforms: string | null;
  collections: string | null;
  created_at: string | null;
  feedback_count: string | null;
  groups: string | null;
  id: number | null;
  identifier_count: string | null;
  media_kind: string | null;
  metadata: string | null;
  release_year: number | null;
  runtime_seconds: number | null;
  source_link_count: string | null;
  source_summary_count: string | null;
  updated_at: string | null;
}

export interface MediaItemIdentifiers {
  id: Generated<number | null>;
  identifier_type: string;
  identifier_value: string;
  is_primary: Generated<number>;
  item_id: number;
  metadata: string | null;
  provider: string;
}

export interface MediaItems {
  canonical_title: string;
  created_at: Generated<string>;
  id: Generated<number | null>;
  media_kind: string;
  metadata: string | null;
  release_year: number | null;
  runtime_seconds: number | null;
  updated_at: Generated<string>;
}

export interface MediaItemSafeEnrichmentDetails {
  approved_source_link_count: string | null;
  canonical_title: string | null;
  cluster_watched_count: string | null;
  cluster_watchlist_count: string | null;
  first_activity_at: string | null;
  item_id: number | null;
  last_activity_at: string | null;
  letterboxd_movie_ids: string | null;
  letterboxd_uris: string | null;
  media_kind: string | null;
  raw_link_watched_count: string | null;
  raw_link_watchlist_count: string | null;
  release_year: number | null;
  runtime_seconds: number | null;
  source_summary_count: string | null;
}

export interface MediaItemSourceLinks {
  confidence: Generated<number>;
  created_at: Generated<string>;
  id: Generated<number | null>;
  item_id: number;
  link_type: string;
  metadata: string | null;
  source_row_id: number;
  source_table: string;
}

export interface MediaItemSourceSummaries {
  created_at: Generated<string>;
  first_activity_at: string | null;
  item_id: number;
  last_activity_at: string | null;
  liked_count: Generated<number | null>;
  metadata: string | null;
  rated_count: Generated<number | null>;
  reviewed_count: Generated<number | null>;
  source_key: string;
  source_scope: string;
  source_table: string;
  updated_at: Generated<string>;
  watched_count: Generated<number | null>;
  watchlist_count: Generated<number | null>;
}

export interface MediaItemTags {
  confidence: Generated<number>;
  created_at: Generated<string>;
  item_id: number;
  metadata: string | null;
  provider: string;
  source_row_id: number;
  source_table: string;
  tag: string;
}

export interface MediaLibrary {
  activity_count: string | null;
  canonical_title: string | null;
  collection_entry_count: string | null;
  collection_names: string | null;
  collection_platforms: string | null;
  diary_count: string | null;
  feedback_count: string | null;
  feedback_providers: string | null;
  first_activity_at: string | null;
  item_id: number | null;
  last_activity_at: string | null;
  media_kind: string | null;
  metadata: string | null;
  preferences: string | null;
  ratings: string | null;
  release_year: number | null;
  runtime_seconds: number | null;
  watched_count: string | null;
  watchlisted_count: string | null;
}

export interface MediaLog {
  author: string | null;
  consumed_at: string | null;
  created_at: Generated<string>;
  episode: number | null;
  id: Generated<number | null>;
  letterboxd_uri: string | null;
  media_type: string;
  notes: string | null;
  rating: number | null;
  rewatch_count: Generated<number | null>;
  season: number | null;
  source: string | null;
  starred: Generated<number | null>;
  status: Generated<string>;
  title: string;
  year: number | null;
}

export interface MediaPodcastPlays {
  end_time: string | null;
  episode_name: string | null;
  id: string | null;
  ms_played: string | null;
  show_name: string | null;
  source: string | null;
  spotify_episode_uri: string | null;
  spotify_track_uri: string | null;
}

export interface MediaSubscriptions {
  account_id: number | null;
  created_at: Generated<string>;
  creator_id: string | null;
  creator_name: string | null;
  creator_url: string | null;
  id: Generated<number | null>;
  metadata: string | null;
  person_id: number;
  platform: string | null;
  source: string | null;
  subscribed_at: string | null;
}

export interface MediaYoutube {
  list: string | null;
  "Playlist Video Creation Timestamp": string | null;
  "Video ID": string | null;
}

export interface MediaYoutubeMusicSongs {
  album_title: string | null;
  artist_name_1: string | null;
  artist_name_2: string | null;
  artist_name_3: string | null;
  artist_name_4: string | null;
  artist_name_5: string | null;
  created_at: Generated<string>;
  id: Generated<number | null>;
  song_title: string;
  video_id: string | null;
}

export interface MediaYoutubePlaylists {
  add_new_videos_to_top: string | null;
  create_timestamp: string | null;
  created_at: Generated<string>;
  description: string | null;
  id: Generated<number | null>;
  image_height: string | null;
  image_timestamp: string | null;
  image_url: string | null;
  image_width: string | null;
  playlist_id: string | null;
  title: string | null;
  title_language: string | null;
  update_timestamp: string | null;
  video_order: string | null;
  visibility: string | null;
}

export interface MonthlyExpenseItems {
  cadence: string | null;
  cancelled: number | null;
  category: string | null;
  id: Generated<number | null>;
  name: string | null;
  price: number | null;
  source_file: string;
}

export interface MusicAlbums {
  artist_id: number | null;
  created_at: Generated<string>;
  genre: string | null;
  id: Generated<number | null>;
  release_date: string | null;
  spotify_id: string | null;
  title: string;
}

export interface MusicArtists {
  created_at: Generated<string>;
  id: Generated<number | null>;
  name: string;
  sort_name: string | null;
  spotify_id: string | null;
}

export interface MusicListening {
  album: string | null;
  artist: string;
  created_at: Generated<string>;
  id: Generated<number | null>;
  listened_at: string | null;
  notes: string | null;
  source: string | null;
  track: string | null;
}

export interface MusicPlayHistory {
  artist_name: string | null;
  id: Generated<number | null>;
  interaction_type: string | null;
  ms_played: number | null;
  original_id: string | null;
  platform: string;
  played_at: string;
  reason_end: string | null;
  reason_start: string | null;
  shuffle: number | null;
  skipped: number | null;
  source_table: string | null;
  track_id: number | null;
  track_name: string | null;
}

export interface MusicPlaylistItems {
  added_at: string | null;
  artist_name: string | null;
  id: Generated<number | null>;
  playlist_id: number;
  position: number | null;
  track_id: number | null;
  track_name: string | null;
}

export interface MusicPlaylists {
  created_at: string | null;
  description: string | null;
  id: Generated<number | null>;
  is_favorite: Generated<number | null>;
  name: string | null;
  slug: string;
  updated_at: string | null;
  visibility: string | null;
}

export interface MusicPurchases {
  created_at: Generated<string>;
  device_details: string | null;
  id: Generated<number | null>;
  purchased_at: string | null;
  seller: string | null;
  title: string | null;
}

export interface MusicSongs {
  album: string | null;
  artist: string;
  artist_id: number;
  created_at: Generated<string>;
  first_seen_at: string | null;
  id: Generated<number | null>;
  title: string;
  updated_at: Generated<string>;
}

export interface MusicTracks {
  album_id: number | null;
  artist_id: number | null;
  bpm: number | null;
  composer: string | null;
  content_type: string | null;
  created_at: Generated<string>;
  date_added_to_library: string | null;
  disc_number: number | null;
  duration_ms: number | null;
  enriched_at: string | null;
  genre: string | null;
  genres: string | null;
  id: Generated<number | null>;
  is_compilation: Generated<number | null>;
  is_purchased: Generated<number | null>;
  last_modified_date: string | null;
  last_played_at: string | null;
  like_rating: string | null;
  play_count: Generated<number | null>;
  popularity: number | null;
  preview_url: string | null;
  rating: number | null;
  release_date: string | null;
  skip_count: Generated<number | null>;
  sort_album: string | null;
  sort_artist: string | null;
  sort_title: string | null;
  spotify_id: string | null;
  title: string;
  track_number: number | null;
  updated_at: Generated<string>;
}

export interface MyfitnesspalActivities {
  "Activity type": string | null;
  Data: string | null;
  from: string | null;
  "from (manual)": string | null;
  GPS: string | null;
  Modified: string | null;
  Timezone: string | null;
  to: string | null;
  "to (manual)": string | null;
}

export interface MyfitnesspalAggregatesCaloriesEarned {
  date: string | null;
  value: string | null;
}

export interface MyfitnesspalAggregatesCaloriesPassive {
  date: string | null;
  value: string | null;
}

export interface MyfitnesspalAggregatesDistance {
  date: string | null;
  value: string | null;
}

export interface MyfitnesspalAggregatesElevation {
  date: string | null;
  value: string | null;
}

export interface MyfitnesspalAggregatesSteps {
  date: string | null;
  value: string | null;
}

export interface MyfitnesspalBp {
  Comments: string | null;
  Date: string | null;
  Diastolic: string | null;
  "Heart rate": string | null;
  Systolic: string | null;
}

export interface MyfitnesspalHeight {
  Comments: string | null;
  Date: string | null;
  "Height (in)": string | null;
}

export interface MyfitnesspalRawTrackerCaloriesEarned {
  duration: string | null;
  start: string | null;
  value: string | null;
}

export interface MyfitnesspalRawTrackerDistance {
  duration: string | null;
  start: string | null;
  value: string | null;
}

export interface MyfitnesspalRawTrackerElevation {
  duration: string | null;
  start: string | null;
  value: string | null;
}

export interface MyfitnesspalRawTrackerHr {
  duration: string | null;
  start: string | null;
  value: string | null;
}

export interface MyfitnesspalRawTrackerSteps {
  duration: string | null;
  start: string | null;
  value: string | null;
}

export interface NetWorthSnapshots {
  id: Generated<number | null>;
}

export interface Notes {
  content: string | null;
  created_at: string | null;
  folder: string | null;
  id: string | null;
  linked_to: string | null;
  note_type: string | null;
  source_file: string | null;
  tags: string | null;
  title: string | null;
  updated_at: string | null;
}

export interface OpenrouterActivity {
  api_key_name: string | null;
  app_name: string | null;
  byok_usage_inference: number | null;
  cancelled: number | null;
  cost_cache: number | null;
  cost_file_processing: number | null;
  cost_total: number | null;
  cost_web_search: number | null;
  created_at: string | null;
  finish_reason_normalized: string | null;
  finish_reason_raw: string | null;
  generation_id: string | null;
  generation_time_ms: number | null;
  imported_at: Generated<string>;
  model_permaslug: string | null;
  provider_name: string | null;
  source_file: string;
  streamed: number | null;
  time_to_first_token_ms: number | null;
  tokens_cached: number | null;
  tokens_completion: number | null;
  tokens_prompt: number | null;
  tokens_reasoning: number | null;
  user: string | null;
  variant: string | null;
}

export interface PaymentMethods {
  country: string | null;
  creation_date: string | null;
  id: string | null;
  payment_method: string | null;
  postal_code: string | null;
  provider: string | null;
  source: string | null;
}

export interface People {
  age: number | null;
  attractiveness_score: number | null;
  birthdate: string | null;
  birthplace: string | null;
  created_at: string | null;
  diet: string | null;
  display_name: string | null;
  education: string | null;
  first_name: string | null;
  had_sex: number | null;
  id: Generated<number>;
  kissed: number | null;
  last_name: string | null;
  location: string | null;
  middle_name: string | null;
  notes: string | null;
  person_type: string | null;
  profession: string | null;
  relation: string | null;
  relationship_details: string | null;
  relationship_ended_at: string | null;
  relationship_started_at: string | null;
  updated_at: string | null;
}

export interface PeopleContacts {
  created_at: string | null;
  email: string | null;
  extra: string | null;
  first_name: string | null;
  id: string | null;
  last_name: string | null;
  linkedin_url: string | null;
  name: string | null;
  notes: string | null;
  organization: string | null;
  phone: string | null;
  source_db: string | null;
  source_file: string | null;
  sqlite_id: string | null;
  title: string | null;
  updated_at: string | null;
  user_id: string | null;
}

export interface PeopleCurrentBackup {
  first_name: string | null;
  id: string | null;
  last_name: string | null;
  middle_name: string | null;
  notes: string | null;
}

export interface PeopleFamily {
  birthdate: string | null;
  birthplace: string | null;
  id: string | null;
  name: string | null;
  relation: string | null;
}

export interface PeopleRelationships {
  age: string | null;
  attractiveness_score: string | null;
  date_ended: string | null;
  date_started: string | null;
  details: string | null;
  diet: string | null;
  education: string | null;
  id: string | null;
  kiss: string | null;
  location: string | null;
  name: string | null;
  profession: string | null;
  sex: string | null;
}

export interface Periodicals {
  author: string | null;
  category: string | null;
  cover_url: string | null;
  created_at: Generated<string>;
  date_read: string | null;
  id: Generated<number | null>;
  issue: string | null;
  source: Generated<string | null>;
  status: Generated<string | null>;
  title: string;
}

export interface PersonAliases {
  alias: string;
  created_at: Generated<string>;
  id: Generated<number | null>;
  person_id: number;
}

export interface PersonalSizes {
  id: string | null;
  mm: string | null;
  size: string | null;
  type: string | null;
  uk_size: string | null;
  us_size: string | null;
}

export interface PersonDevices {
  account_id: number | null;
  brand: string | null;
  created_at: Generated<string>;
  device_type: string | null;
  display_name: string | null;
  id: Generated<number | null>;
  last_seen_at: string | null;
  last_seen_location: string | null;
  metadata: string | null;
  model_identifier: string | null;
  model_name: string | null;
  os_name: string | null;
  os_version: string | null;
  person_id: number;
  source: string | null;
}

export interface PersonEmails {
  created_at: Generated<string>;
  email: string;
  id: Generated<number | null>;
  is_primary: Generated<number>;
  person_id: number;
  source: string | null;
}

export interface PersonOrganizations {
  created_at: Generated<string>;
  id: Generated<number | null>;
  is_primary: Generated<number>;
  organization: string;
  person_id: number;
  source: string | null;
}

export interface PersonPhones {
  created_at: Generated<string>;
  id: Generated<number | null>;
  is_primary: Generated<number>;
  person_id: number;
  phone_number: string;
}

export interface PhoneNumbers {
  id: string | null;
  location: string | null;
  phone_number: string | null;
}

export interface Place {
  address: string | null;
  best_for: string | null;
  business_status: string | null;
  createdAt: string | null;
  description: string | null;
  google_maps_id: string | null;
  id: string | null;
  imageUrl: string | null;
  is_public: string | null;
  itemId: string | null;
  latitude: string | null;
  location: string | null;
  longitude: string | null;
  name: string | null;
  opening_hours: string | null;
  phoneNumber: string | null;
  photos: string | null;
  priceLevel: string | null;
  rating: string | null;
  types: string | null;
  updatedAt: string | null;
  websiteUri: string | null;
  wifi_info: string | null;
}

export interface PlaceCollectionItems {
  collection_id: number;
  comment: string | null;
  created_at: Generated<string>;
  id: Generated<number | null>;
  metadata: string | null;
  note: string | null;
  place_id: number;
  saved_at: string | null;
  source_row_id: number | null;
  source_table: string | null;
  updated_at: Generated<string>;
  url: string | null;
}

export interface PlaceCollections {
  account_id: number | null;
  collection_type: string | null;
  created_at: Generated<string>;
  description: string | null;
  id: Generated<number | null>;
  metadata: string | null;
  name: string;
  person_id: number;
  platform: string | null;
  source: string | null;
  updated_at: Generated<string>;
}

export interface PlaceDetails {
  city: string | null;
  collection_entry_count: string | null;
  collections: string | null;
  country: string | null;
  country_code: string | null;
  created_at: string | null;
  event_count: string | null;
  first_event_start: string | null;
  formatted_address: string | null;
  geocoded_at: string | null;
  id: number | null;
  last_event_start: string | null;
  latitude: number | null;
  longitude: number | null;
  metadata: string | null;
  name: string | null;
  place_type: string | null;
  postal_code: string | null;
  state: string | null;
  updated_at: string | null;
  url: string | null;
}

export interface PlaceGeocodeAttempts {
  created_at: Generated<string>;
  id: Generated<number | null>;
  place_id: number;
  provider: Generated<string>;
  query: string;
  response_json: string | null;
  result_summary: string | null;
  status: string;
}

export interface PlaceGeocodeState {
  created_at: Generated<string>;
  last_geocode_query: string | null;
  last_geocode_result_summary: string | null;
  last_geocode_status: string | null;
  place_id: Generated<number | null>;
  updated_at: Generated<string>;
}

export interface PlaceReviewState {
  created_at: Generated<string>;
  place_id: Generated<number | null>;
  review_decision_at: string | null;
  review_decision_source: string | null;
  review_query: string | null;
  review_reason: string | null;
  review_status: string | null;
  review_updated_at: string | null;
  updated_at: Generated<string>;
}

export interface Places {
  city: string | null;
  country: string | null;
  country_code: string | null;
  created_at: Generated<string>;
  formatted_address: string | null;
  geocoded_at: string | null;
  id: Generated<number | null>;
  last_geocode_query: string | null;
  last_geocode_result_summary: string | null;
  last_geocode_status: string | null;
  latitude: number | null;
  longitude: number | null;
  metadata: string | null;
  name: string;
  place_type: string | null;
  postal_code: string | null;
  review_decision_at: string | null;
  review_decision_source: string | null;
  review_query: string | null;
  review_reason: string | null;
  review_status: string | null;
  review_updated_at: string | null;
  state: string | null;
  updated_at: Generated<string>;
  url: string | null;
}

export interface PlacesHotels {
  check_in_date: string | null;
  check_out_date: string | null;
  city: string | null;
  country: string | null;
  hotel_name: string | null;
  id: string | null;
  location_id: string | null;
  notes: string | null;
  number_of_travelers: string | null;
  price: string | null;
  state: string | null;
  status: string | null;
  trip_id: string | null;
}

export interface PlaceVisits {
  address: string | null;
  created_at: Generated<string | null>;
  id: string | null;
  meal: string | null;
  name: string | null;
  notes: string | null;
  people: string | null;
  place_id: number | null;
  source: string | null;
  source_id: string | null;
  visited_at: string | null;
}

export interface PlanningObjectives {
  domain: string | null;
  id: string | null;
  name: string | null;
}

export interface PlanningResults {
  blocked_by: string | null;
  blocking: string | null;
  category: string | null;
  date: string | null;
  id: string | null;
  name: string | null;
  objectives: string | null;
  parent_item: string | null;
  status: string | null;
  sub_item: string | null;
  type: string | null;
}

export interface Possessions {
  acquired_date: string | null;
  amount: string | null;
  amount_unit: string | null;
  artist: string | null;
  brand: string | null;
  category: string | null;
  color: string | null;
  daily_cost: string | null;
  days_owned: string | null;
  id: string | null;
  image_url: string | null;
  metadata: string | null;
  model: string | null;
  name: string | null;
  net_value: string | null;
  notes: string | null;
  placement: string | null;
  possession_type: string | null;
  price: string | null;
  retired_date: string | null;
  sell_price: string | null;
  serial_number: string | null;
  size: string | null;
  source_row_id: number | null;
  source_table: string | null;
  status: string | null;
  sub_category: string | null;
  url: string | null;
}

export interface PossessionsAcquisition {
  id: string | null;
  timestamp: string | null;
  value: string | null;
}

export interface PossessionsContainers {
  id: string | null;
  label: string | null;
  possession_id: string | null;
  tare_weight_g: string | null;
  type: string | null;
}

export interface PossessionsCrystals {
  Crystal: string | null;
  Identification: string | null;
  "Metaphysical Meaning & Use": string | null;
}

export interface PossessionsUsage {
  amount: string | null;
  amount_unit: string | null;
  container_id: string | null;
  end_date: string | null;
  id: string | null;
  method: string | null;
  possession_id: string | null;
  start_date: string | null;
  timestamp: string | null;
  type: string | null;
}

export interface PossessionsUsageLog {
  amount: string | null;
  amount_per_day: string | null;
  container_id: string | null;
  end_date: string | null;
  id: string | null;
  start_date: string | null;
  timestamp: string | null;
  type: string | null;
}

export interface PossessionsVideoGames {
  acquired_date: string | null;
  category: string | null;
  id: string | null;
  name: string | null;
  notes: string | null;
  platform: string | null;
  possession_type: string | null;
  release_year: string | null;
  source_row_id: number | null;
  source_table: string | null;
  status: string | null;
  sub_category: string | null;
}

export interface Projects {
  address: string | null;
  blocked_by: string | null;
  company: string | null;
  completion: string | null;
  contact_name: string | null;
  currency: string | null;
  date_range_text: string | null;
  domain: string | null;
  end_date: string | null;
  end_salary: number | null;
  id: Generated<number>;
  is_blocking: string | null;
  name: string | null;
  owner: string | null;
  phone_number: string | null;
  position: string | null;
  priority: string | null;
  record_type: string;
  start_date: string | null;
  start_salary: number | null;
  status: string | null;
  summary: string | null;
  tasks: string | null;
  url: string | null;
}

export interface Purchases {
  created_at: Generated<string>;
  id: Generated<number | null>;
  notes: string | null;
  order_number: string | null;
  price: number | null;
  product_name: string;
  purchased_at: string | null;
  serial_number: string | null;
}

export interface ReadingSessions {
  asin: string | null;
  book_id: number | null;
  created_at: Generated<string>;
  duration_ms: number | null;
  ended_at: string | null;
  id: Generated<number | null>;
  source: Generated<string | null>;
  started_at: string | null;
}

export interface Residences {
  address: string | null;
  contact_email: string | null;
  contact_number: string | null;
  end_date: string | null;
  end_rent: string | null;
  id: string | null;
  sqft: string | null;
  start_date: string | null;
  start_rent: string | null;
}

export interface Runway {
  available_funds: number | null;
  date: string | null;
  id: Generated<number>;
  weight: number | null;
}

export interface Schools {
  end_date: string | null;
  id: string | null;
  name: string | null;
  start_date: string | null;
}

export interface Searches {
  id: Generated<number>;
  interaction_uris: string | null;
  platform: string | null;
  query: string | null;
  search_time: string | null;
  source: string | null;
}

export interface SearchIndex {
  content: Generated<string>;
  created_at: Generated<string | null>;
  domain: string;
  entity_id: string;
  entity_type: string;
  tags: Generated<string>;
  title: string;
}

export interface Services {
  address: string | null;
  company: string | null;
  id: string | null;
  password_changed: string | null;
}

export interface SignalAccount {
  account_settings_json: string | null;
  family_name: string | null;
  given_name: string | null;
  id: Generated<number | null>;
  imported_at: Generated<string>;
  profile_key: string | null;
  raw_json: string;
  source_file: string;
  username: string | null;
}

export interface SignalChatFolders {
  folder_type: string | null;
  id: string | null;
  imported_at: Generated<string>;
  include_all_group_chats: number | null;
  include_all_individual_chats: number | null;
  raw_json: string;
  show_muted_chats: number | null;
  source_file: string;
}

export interface SignalChatItems {
  author_id: string | null;
  chat_id: string | null;
  date_sent: string | null;
  directionless: number | null;
  id: Generated<number | null>;
  imported_at: Generated<string>;
  raw_json: string;
  source_file: string;
  update_message_json: string | null;
}

export interface SignalChats {
  expire_timer_version: number | null;
  id: string | null;
  imported_at: Generated<string>;
  raw_json: string;
  recipient_id: string | null;
  source_file: string;
}

export interface SignalRecipients {
  contact_json: string | null;
  e164: string | null;
  id: string | null;
  imported_at: Generated<string>;
  pni: string | null;
  raw_json: string;
  source_file: string;
}

export interface SignalRecords {
  id: Generated<number | null>;
  imported_at: Generated<string>;
  raw_json: string;
  record_type: string;
  source_file: string;
  source_line: number;
}

export interface SignalStickerPacks {
  imported_at: Generated<string>;
  pack_id: string | null;
  pack_key: string | null;
  raw_json: string;
  source_file: string;
}

export interface SocialAccounts {
  created_at: Generated<string>;
  id: Generated<number | null>;
  kind: string;
  metadata: string | null;
  name: string;
  platform: string;
  timestamp: string | null;
}

export interface SocialComments {
  id: string | null;
  platform: string | null;
  text: string | null;
  timestamp: string | null;
  username: string | null;
}

export interface SocialConnections {
  connection_type: string | null;
  id: string | null;
  platform: string | null;
  timestamp: string | null;
  username: string | null;
}

export interface SocialLikes {
  id: string | null;
  platform: string | null;
  reaction: string | null;
  target_type: string | null;
  target_username: string | null;
  timestamp: string | null;
}

export interface SocialMedia {
  handle: string | null;
  id: string | null;
  platform: string | null;
}

export interface SocialMessages {
  id: string | null;
  media_url: string | null;
  metadata: string | null;
  platform: string | null;
  receiver: string | null;
  sender: string | null;
  story_share: string | null;
  text: string | null;
  timestamp: string | null;
}

export interface SocialPosts {
  caption: string | null;
  id: string | null;
  location: string | null;
  media_url: string | null;
  metadata: string | null;
  path: string | null;
  platform: string | null;
  post_type: string | null;
  timestamp: string | null;
}

export interface SpotifyStreamingHistory {
  artistName: string | null;
  endTime: string | null;
  msPlayed: number | null;
  trackName: string | null;
}

export interface Tags {
  color: string | null;
  description: string | null;
  domain: string | null;
  extra: string | null;
  id: string | null;
  name: string | null;
  source_db: string | null;
  sqlite_id: string | null;
  usage_count: string | null;
  user_id: string | null;
}

export interface TarotReadings {
  card: string | null;
  date: string | null;
  id: string | null;
  notes: string | null;
}

export interface Tasks {
  completed: Generated<number | null>;
  completed_at: string | null;
  created_at: string | null;
  description: string | null;
  due_date: string | null;
  estimate: string | null;
  id: string | null;
  list: string | null;
  parent_id: string | null;
  priority: Generated<number | null>;
  project: string | null;
  recurrence: string | null;
  section: string | null;
  section_id: string | null;
  source_id: string | null;
  status: Generated<string | null>;
  tags: string | null;
  title: string;
}

export interface TasksHominem {
  tags: string | null;
  ui_screen_type: string | null;
  user_story: string | null;
}

export interface TasksKensho {
  Assignee: string | null;
  Comment: string | null;
  Comment_1: string | null;
  Comment_2: string | null;
  Comment_3: string | null;
  Comment_4: string | null;
  Components: string | null;
  Components_1: string | null;
  Components_2: string | null;
  Created: string | null;
  Creator: string | null;
  "Custom field ([CHART] Date of First Response)": string | null;
  "Custom field (Additional Information)": string | null;
  "Custom field (Business Sponsor)": string | null;
  "Custom field (Can the project be sent to the offshore teams?)": string | null;
  "Custom field (Can the project proceed?)": string | null;
  "Custom field (Checklist Completed)": string | null;
  "Custom field (Checklist Content YAML)": string | null;
  "Custom field (Checklist Progress)": string | null;
  "Custom field (Checklist Text)": string | null;
  "Custom field (CIQ Key Dev Type)": string | null;
  "Custom field (Customer Request Type)": string | null;
  "Custom field (Deadline)": string | null;
  "Custom field (Delivery Date)": string | null;
  "Custom field (Description - Kubernetes)": string | null;
  "Custom field (Description - New Project)": string | null;
  "Custom field (Description-Jenkins)": string | null;
  "Custom field (Development)": string | null;
  "Custom field (Difficulty)": string | null;
  "Custom field (DQ Effort)": string | null;
  "Custom field (DQ time costs (days))": string | null;
  "Custom field (Epic Color)": string | null;
  "Custom field (Epic Link)": string | null;
  "Custom field (Epic Name)": string | null;
  "Custom field (Epic Status)": string | null;
  "Custom field (Escalation outcome)": string | null;
  "Custom field (Event Requested)": string | null;
  "Custom field (Events Team Effort)": string | null;
  "Custom field (Events Team time cost (days))": string | null;
  "Custom field (Eventset Name)": string | null;
  "Custom field (Frequency of Event)": string | null;
  "Custom field (Full set annotation agreement?)": string | null;
  "Custom field (Happy Meter)": string | null;
  "Custom field (Instrument)": string | null;
  "Custom field (Issue color)": string | null;
  "Custom field (Kensho Event Type)": string | null;
  "Custom field (Komitto Name)": string | null;
  "Custom field (ML Team Effort)": string | null;
  "Custom field (ML Team time cost (days))": string | null;
  "Custom field (Model performance?)": string | null;
  "Custom field (Model predictions are reasonable?)": string | null;
  "Custom field (Model spec approved?)": string | null;
  "Custom field (Outcome)": string | null;
  "Custom field (Post-mortem Link)": string | null;
  "Custom field (Primary Source URL)": string | null;
  "Custom field (Rank)": string | null;
  "Custom field (Request participants)": string | null;
  "Custom field (Requested By)": string | null;
  "Custom field (Requester Email)": string | null;
  "Custom field (Requester Email)_1": string | null;
  "Custom field (Requesting Institution)": string | null;
  "Custom field (Retraining necessary?)": string | null;
  "Custom field (Secondary Source URL)": string | null;
  "Custom field (Specification Due Date)": string | null;
  "Custom field (Start date)": string | null;
  "Custom field (Story point estimate)": string | null;
  "Custom field (Story Points)": string | null;
  "Custom field (Tech Point)": string | null;
  "Custom field (Time to resolution)": string | null;
  "Custom field (Trial set annotation agreement?)": string | null;
  "Custom field (User Feedback)": string | null;
  "Custom field (VSTS Link)": string | null;
  "Custom field (Why Would Someone Care?)": string | null;
  Description: string | null;
  "Due date": string | null;
  Environment: string | null;
  "Issue id": string | null;
  "Issue key": string | null;
  "Issue Type": string | null;
  "Last Viewed": string | null;
  "Original Estimate": string | null;
  Priority: string | null;
  "Project description": string | null;
  "Project key": string | null;
  "Project lead": string | null;
  "Project name": string | null;
  "Project type": string | null;
  "Project url": string | null;
  "Remaining Estimate": string | null;
  Reporter: string | null;
  Resolution: string | null;
  Resolved: string | null;
  "Satisfaction rating": string | null;
  "Security Level": string | null;
  Status: string | null;
  Summary: string | null;
  "Time Spent": string | null;
  Updated: string | null;
  Votes: string | null;
  Watchers: string | null;
  Watchers_1: string | null;
  Watchers_2: string | null;
  Watchers_3: string | null;
  "Work Ratio": string | null;
  "Σ Original Estimate": string | null;
  "Σ Remaining Estimate": string | null;
  "Σ Time Spent": string | null;
}

export interface TasksProlog {
  Archived: string | null;
  Assignee: string | null;
  Canceled: string | null;
  Completed: string | null;
  Created: string | null;
  Creator: string | null;
  "Cycle End": string | null;
  "Cycle Name": string | null;
  "Cycle Number": string | null;
  "Cycle Start": string | null;
  Description: string | null;
  "Due Date": string | null;
  Estimate: string | null;
  ID: string | null;
  Initiatives: string | null;
  Labels: string | null;
  "Parent issue": string | null;
  Priority: string | null;
  Project: string | null;
  "Project ID": string | null;
  "Project Milestone": string | null;
  "Project Milestone ID": string | null;
  Roadmaps: string | null;
  "SLA Status": string | null;
  Started: string | null;
  Status: string | null;
  Team: string | null;
  Title: string | null;
  Triaged: string | null;
  Updated: string | null;
}

export interface Tattoos {
  artist: string | null;
  cost_cents: number | null;
  created_at: Generated<string>;
  date: string | null;
  description: string;
  id: Generated<number | null>;
  location: string | null;
  notes: string | null;
  studio: string | null;
}

export interface Transactions {
  account_id: string;
  amount: number;
  category: string | null;
  created_at: Generated<string>;
  date: string;
  description: string | null;
  id: string | null;
  type: string;
}

export interface Transportation {
  cost: string | null;
  date: string | null;
  from_location: string | null;
  id: string | null;
  notes: string | null;
  to_location: string | null;
  transportation_type_id: string | null;
  trip_id: string | null;
  type: string | null;
}

export interface TransportationTypes {
  category: string | null;
  created_at: string | null;
  description: string | null;
  id: string | null;
  name: string | null;
}

export interface TripAttendees {
  person_id: string | null;
  role: string | null;
  trip_id: string | null;
}

export interface TripCategories {
  category: string | null;
  created_at: string | null;
  id: string | null;
  trip_id: string | null;
}

export interface Trips {
  city: string | null;
  country: string | null;
  created_at: string | null;
  end_date: string | null;
  extra: string | null;
  id: string | null;
  location_id: string | null;
  name: string | null;
  num_of_travelers: string | null;
  people: string | null;
  price: string | null;
  source_db: string | null;
  sqlite_id: string | null;
  start_date: string | null;
  state: string | null;
  travel_details: string | null;
  updated_at: string | null;
  user_id: string | null;
}

export interface TripTags {
  created_at: string | null;
  id: string | null;
  tag: string | null;
  trip_id: string | null;
}

export interface TurbotaxFiling {
  app_name: string | null;
  authId: string | null;
  filingId: string | null;
  filingType: string | null;
  postmark: string | null;
  rxTimestamp: string | null;
  tax_year: string | null;
}

export interface TurbotaxFilingOrder {
  accountAuthId: string | null;
  accountEmail: string | null;
  accountFamilyName: string | null;
  accountGivenName: string | null;
  accountId: string | null;
  accountMiddleName: string | null;
  accountOrganizationEmail: string | null;
  accountOrganizationName: string | null;
  accountOrganizationPhoneNumber: string | null;
  accountPhoneNumber: string | null;
  addressLine1: string | null;
  addressLine2: string | null;
  addressLine3: string | null;
  city: string | null;
  country: string | null;
  createdDate: string | null;
  locality: string | null;
  orderNumber: string | null;
  orderStatus: string | null;
  paymentAuthorizationIds: string | null;
  paymentMethodAttributes: string | null;
  paymentMethodCategory: string | null;
  paymentMethods: string | null;
  postalCode: string | null;
  postalExt: string | null;
  region: string | null;
  stateOrProvince: string | null;
  subRegion: string | null;
  tax_year: string | null;
}

export interface TurbotaxFilingStates {
  filingId: string | null;
  filingState: string | null;
  filingType: string | null;
  message: string | null;
  timeStamp: string | null;
}

export interface UserLists {
  createdAt: string | null;
  listId: string | null;
  updatedAt: string | null;
  userId: string | null;
}

export interface Users {
  better_auth_user_id: string | null;
  birthday: string | null;
  createdAt: string | null;
  email: string | null;
  emailVerified: string | null;
  id: string | null;
  image: string | null;
  isAdmin: string | null;
  name: string | null;
  photo_url: string | null;
  primary_auth_subject_id: string | null;
  supabase_id: string | null;
  updatedAt: string | null;
}

export interface DB {
  account_activity_log: AccountActivityLog;
  account_aliases: AccountAliases;
  account_name_map: AccountNameMap;
  accounts: Accounts;
  activities: Activities;
  activity_event_map: ActivityEventMap;
  activity_log: ActivityLog;
  activity_people: ActivityPeople;
  activity_types: ActivityTypes;
  amazon_orders: AmazonOrders;
  amazon_purchases: AmazonPurchases;
  amazon_returns: AmazonReturns;
  art: Art;
  artist_profiles: ArtistProfiles;
  artworks: Artworks;
  book_highlights: BookHighlights;
  book_shelves: BookShelves;
  bookmarks: Bookmarks;
  books: Books;
  business_planning_inputs: BusinessPlanningInputs;
  business_planning_revenue: BusinessPlanningRevenue;
  cal_import_batches: CalImportBatches;
  calendar_event_categories: CalendarEventCategories;
  calendar_event_details: CalendarEventDetails;
  calendar_event_occurrences: CalendarEventOccurrences;
  calendar_event_people: CalendarEventPeople;
  calendar_event_place_details: CalendarEventPlaceDetails;
  calendar_event_type_mappings: CalendarEventTypeMappings;
  calendar_event_types: CalendarEventTypes;
  calendar_events: CalendarEvents;
  calendar_events_raw: CalendarEventsRaw;
  calendar_summary_map: CalendarSummaryMap;
  calendar_tags: CalendarTags;
  career_application_stages: CareerApplicationStages;
  career_applications: CareerApplications;
  career_company_velocity: CareerCompanyVelocity;
  career_education: CareerEducation;
  career_interviews: CareerInterviews;
  career_offers: CareerOffers;
  career_pipeline: CareerPipeline;
  career_positions: CareerPositions;
  career_profile: CareerProfile;
  career_source_summary: CareerSourceSummary;
  career_stage_timeline: CareerStageTimeline;
  career_stage_velocity: CareerStageVelocity;
  career_weekly_applications: CareerWeeklyApplications;
  concerts: Concerts;
  dining: Dining;
  domains: Domains;
  entities: Entities;
  event_people: EventPeople;
  event_places: EventPlaces;
  event_tags: EventTags;
  events: Events;
  events_fts: EventsFts;
  events_fts_config: EventsFtsConfig;
  events_fts_data: EventsFtsData;
  events_fts_docsize: EventsFtsDocsize;
  events_fts_idx: EventsFtsIdx;
  favorites: Favorites;
  finance_account_labels: FinanceAccountLabels;
  finance_account_ledger_entries: FinanceAccountLedgerEntries;
  finance_account_statement_periods: FinanceAccountStatementPeriods;
  finance_accounts: FinanceAccounts;
  finance_categories: FinanceCategories;
  finance_credit_scores: FinanceCreditScores;
  finance_expenses: FinanceExpenses;
  finance_incomes: FinanceIncomes;
  finance_ledger_entry_annotations: FinanceLedgerEntryAnnotations;
  google_activities: GoogleActivities;
  google_device_registry: GoogleDeviceRegistry;
  google_devices: GoogleDevices;
  google_play_purchases: GooglePlayPurchases;
  google_saved: GoogleSaved;
  goose_db_version: GooseDbVersion;
  health_activities: HealthActivities;
  health_blood_pressure: HealthBloodPressure;
  health_body_composition: HealthBodyComposition;
  health_daily: HealthDaily;
  health_heart_rate: HealthHeartRate;
  health_height_measurements: HealthHeightMeasurements;
  health_locations: HealthLocations;
  health_log: HealthLog;
  health_records: HealthRecords;
  health_sleep: HealthSleep;
  health_supplements: HealthSupplements;
  health_tracker: HealthTracker;
  health_vitamins: HealthVitamins;
  health_weight_measurements: HealthWeightMeasurements;
  hinge_media: HingeMedia;
  hinge_prompts: HingePrompts;
  hinge_user: HingeUser;
  income_log: IncomeLog;
  item: Item;
  life_events: LifeEvents;
  list: List;
  list_invite: ListInvite;
  llm_conversations: LlmConversations;
  llm_messages: LlmMessages;
  locations_cities: LocationsCities;
  media_activity_log: MediaActivityLog;
  media_backlog: MediaBacklog;
  media_collection_items: MediaCollectionItems;
  media_collections: MediaCollections;
  media_games: MediaGames;
  media_item_activities: MediaItemActivities;
  media_item_activity_details: MediaItemActivityDetails;
  media_item_details: MediaItemDetails;
  media_item_identifiers: MediaItemIdentifiers;
  media_item_safe_enrichment_details: MediaItemSafeEnrichmentDetails;
  media_item_source_links: MediaItemSourceLinks;
  media_item_source_summaries: MediaItemSourceSummaries;
  media_item_tags: MediaItemTags;
  media_items: MediaItems;
  media_library: MediaLibrary;
  media_log: MediaLog;
  media_podcast_plays: MediaPodcastPlays;
  media_subscriptions: MediaSubscriptions;
  media_youtube: MediaYoutube;
  media_youtube_music_songs: MediaYoutubeMusicSongs;
  media_youtube_playlists: MediaYoutubePlaylists;
  monthly_expense_items: MonthlyExpenseItems;
  music_albums: MusicAlbums;
  music_artists: MusicArtists;
  music_listening: MusicListening;
  music_play_history: MusicPlayHistory;
  music_playlist_items: MusicPlaylistItems;
  music_playlists: MusicPlaylists;
  music_purchases: MusicPurchases;
  music_songs: MusicSongs;
  music_tracks: MusicTracks;
  myfitnesspal_activities: MyfitnesspalActivities;
  myfitnesspal_aggregates_calories_earned: MyfitnesspalAggregatesCaloriesEarned;
  myfitnesspal_aggregates_calories_passive: MyfitnesspalAggregatesCaloriesPassive;
  myfitnesspal_aggregates_distance: MyfitnesspalAggregatesDistance;
  myfitnesspal_aggregates_elevation: MyfitnesspalAggregatesElevation;
  myfitnesspal_aggregates_steps: MyfitnesspalAggregatesSteps;
  myfitnesspal_bp: MyfitnesspalBp;
  myfitnesspal_height: MyfitnesspalHeight;
  myfitnesspal_raw_tracker_calories_earned: MyfitnesspalRawTrackerCaloriesEarned;
  myfitnesspal_raw_tracker_distance: MyfitnesspalRawTrackerDistance;
  myfitnesspal_raw_tracker_elevation: MyfitnesspalRawTrackerElevation;
  myfitnesspal_raw_tracker_hr: MyfitnesspalRawTrackerHr;
  myfitnesspal_raw_tracker_steps: MyfitnesspalRawTrackerSteps;
  net_worth_snapshots: NetWorthSnapshots;
  notes: Notes;
  openrouter_activity: OpenrouterActivity;
  payment_methods: PaymentMethods;
  people: People;
  people_contacts: PeopleContacts;
  people_current_backup: PeopleCurrentBackup;
  people_family: PeopleFamily;
  people_relationships: PeopleRelationships;
  periodicals: Periodicals;
  person_aliases: PersonAliases;
  person_devices: PersonDevices;
  person_emails: PersonEmails;
  person_organizations: PersonOrganizations;
  person_phones: PersonPhones;
  personal_sizes: PersonalSizes;
  phone_numbers: PhoneNumbers;
  place: Place;
  place_collection_items: PlaceCollectionItems;
  place_collections: PlaceCollections;
  place_details: PlaceDetails;
  place_geocode_attempts: PlaceGeocodeAttempts;
  place_geocode_state: PlaceGeocodeState;
  place_review_state: PlaceReviewState;
  place_visits: PlaceVisits;
  places: Places;
  places_hotels: PlacesHotels;
  planning_objectives: PlanningObjectives;
  planning_results: PlanningResults;
  possessions: Possessions;
  possessions_acquisition: PossessionsAcquisition;
  possessions_containers: PossessionsContainers;
  possessions_crystals: PossessionsCrystals;
  possessions_usage: PossessionsUsage;
  possessions_usage_log: PossessionsUsageLog;
  possessions_video_games: PossessionsVideoGames;
  projects: Projects;
  purchases: Purchases;
  reading_sessions: ReadingSessions;
  residences: Residences;
  runway: Runway;
  schools: Schools;
  search_index: SearchIndex;
  searches: Searches;
  services: Services;
  signal_account: SignalAccount;
  signal_chat_folders: SignalChatFolders;
  signal_chat_items: SignalChatItems;
  signal_chats: SignalChats;
  signal_recipients: SignalRecipients;
  signal_records: SignalRecords;
  signal_sticker_packs: SignalStickerPacks;
  social_accounts: SocialAccounts;
  social_comments: SocialComments;
  social_connections: SocialConnections;
  social_likes: SocialLikes;
  social_media: SocialMedia;
  social_messages: SocialMessages;
  social_posts: SocialPosts;
  spotify_streaming_history: SpotifyStreamingHistory;
  tags: Tags;
  tarot_readings: TarotReadings;
  tasks: Tasks;
  tasks_hominem: TasksHominem;
  tasks_kensho: TasksKensho;
  tasks_prolog: TasksProlog;
  tattoos: Tattoos;
  transactions: Transactions;
  transportation: Transportation;
  transportation_types: TransportationTypes;
  trip_attendees: TripAttendees;
  trip_categories: TripCategories;
  trip_tags: TripTags;
  trips: Trips;
  turbotax_filing: TurbotaxFiling;
  turbotax_filing_order: TurbotaxFilingOrder;
  turbotax_filing_states: TurbotaxFilingStates;
  user_lists: UserLists;
  users: Users;
}
